config/routes.rb
Rails.application.routes.draw do
  resources :veiculo_rastreadores
  resources :veiculo_motoristas
  get 'page/index'

  get 'viagens/viagem' => 'viagens#viagem'
  get 'viagens/cria_viagem' => 'viagens#cria_viagem'

  post 'viagens/impcsv' => 'viagens#impcsv'
  get 'viagens/impcsv' => 'viagens#impcsv'

  post 'page/jornada' => 'page#jornada'

  get 'motoristas/autocomplete' => 'motoristas#autocomplete'

  get '/jornadaex' => 'page#jornadaex'

  resources :viagens
  resources :parada_empresas
  resources :ponto_paradas
  resources :tipo_paradas
  resources :eventos
  resources :tipo_eventos
  resources :veiculos
  resources :rastreadores
  resources :motoristas
  resources :empresas

  root 'page#index'

end

app/models/parada_empresa.rb
class ParadaEmpresa < ActiveRecord::Base
  belongs_to :ponto_parada
  belongs_to :empresa
end

app/controllers/parada_empresas_controller.rb
class ParadaEmpresasController < ApplicationController
  before_action :set_parada_empresa, only: [:show, :edit, :update, :destroy]

  # GET /parada_empresas
  # GET /parada_empresas.json
  def index
    @parada_empresas = ParadaEmpresa.all
  end

  # GET /parada_empresas/1
  # GET /parada_empresas/1.json
  def show
  end

  # GET /parada_empresas/new
  def new
    @parada_empresa = ParadaEmpresa.new
  end

  # GET /parada_empresas/1/edit
  def edit
  end

  # POST /parada_empresas
  # POST /parada_empresas.json
  def create
    @parada_empresa = ParadaEmpresa.new(parada_empresa_params)

    respond_to do |format|
      if @parada_empresa.save
        format.html { redirect_to @parada_empresa, notice: 'Parada empresa was successfully created.' }
        format.json { render :show, status: :created, location: @parada_empresa }
      else
        format.html { render :new }
        format.json { render json: @parada_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parada_empresas/1
  # PATCH/PUT /parada_empresas/1.json
  def update
    respond_to do |format|
      if @parada_empresa.update(parada_empresa_params)
        format.html { redirect_to @parada_empresa, notice: 'Parada empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @parada_empresa }
      else
        format.html { render :edit }
        format.json { render json: @parada_empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parada_empresas/1
  # DELETE /parada_empresas/1.json
  def destroy
    @parada_empresa.destroy
    respond_to do |format|
      format.html { redirect_to parada_empresas_url, notice: 'Parada empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parada_empresa
      @parada_empresa = ParadaEmpresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parada_empresa_params
      params.require(:parada_empresa).permit(:ponto_parada_id, :empresa_id)
    end
end

app/helpers/parada_empresas_helper.rb
module ParadaEmpresasHelper
end

app/views/parada_empresas/_form.html.erb
<%= form_for @parada_empresa, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :ponto_parada_id, :class => 'control-label' %>
    <%= f.number_field :ponto_parada_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :empresa_id, :class => 'control-label' %>
    <%= f.number_field :empresa_id, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                parada_empresas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/parada_empresas/edit.html.erb
<%- model_class = ParadaEmpresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parada_empresas/index.html.erb
<%- model_class = ParadaEmpresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ponto_parada_id) %></th>
      <th><%= model_class.human_attribute_name(:empresa_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parada_empresas.each do |parada_empresa| %>
      <tr>
        <td><%= link_to parada_empresa.id, parada_empresa_path(parada_empresa) %></td>
        <td><%= parada_empresa.ponto_parada_id %></td>
        <td><%= parada_empresa.empresa_id %></td>
        <td><%=l parada_empresa.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_parada_empresa_path(parada_empresa), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      parada_empresa_path(parada_empresa),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parada_empresa_path,
            :class => 'btn btn-primary' %>

app/views/parada_empresas/new.html.erb
<%- model_class = ParadaEmpresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parada_empresas/show.html.erb
<%- model_class = ParadaEmpresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ponto_parada_id) %>:</strong></dt>
  <dd><%= @parada_empresa.ponto_parada_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:empresa_id) %>:</strong></dt>
  <dd><%= @parada_empresa.empresa_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              parada_empresas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_parada_empresa_path(@parada_empresa), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              parada_empresa_path(@parada_empresa),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>