config/routes.rb
Rails.application.routes.draw do
  resources :veiculo_rastreadores
  resources :veiculo_motoristas
  get 'page/index'

  get 'viagens/viagem' => 'viagens#viagem'
  get 'viagens/cria_viagem' => 'viagens#cria_viagem'

  post 'viagens/impcsv' => 'viagens#impcsv'
  get 'viagens/impcsv' => 'viagens#impcsv'

  post 'page/jornada' => 'page#jornada'

  get 'motoristas/autocomplete' => 'motoristas#autocomplete'

  get '/jornadaex' => 'page#jornadaex'

  resources :viagens
  resources :parada_empresas
  resources :ponto_paradas
  resources :tipo_paradas
  resources :eventos
  resources :tipo_eventos
  resources :veiculos
  resources :rastreadores
  resources :motoristas
  resources :empresas

  root 'page#index'

end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :motorista
  belongs_to :rastreador
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]

  # GET /veiculos
  # GET /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully created.' }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veiculo_params
      params.require(:veiculo).permit(:empresa_id, :placa, :cor, :status)
    end
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/veiculos/_form.html.erb
<%= form_for @veiculo, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :empresa_id, :class => 'control-label' %>
    <%= f.collection_select(:empresa_id,Empresa.all.order("razao asc"),:id,:razao,{}, :class => 'form-control') %>
  </div>
  <div class="form-group">
    <%= f.label :placa, :class => 'control-label' %>
    <%= f.text_field :placa, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cor, :class => 'control-label' %>
    <%= f.text_field :cor, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "status", :class => 'control-label' %>
    <select name='veiculo[status]' id="veiculo_status" class="form-control"><option value=1>Ativo</option><option value=0>Inativo</option></select>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                veiculos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/veiculos/index.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:empresa_id) %></th>
      <th><%= model_class.human_attribute_name(:motorista_id) %></th>
      <th><%= model_class.human_attribute_name(:placa) %></th>
      <th><%= model_class.human_attribute_name(:rastreador_id) %></th>
      <th><%= model_class.human_attribute_name(:cor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= link_to veiculo.id, veiculo_path(veiculo) %></td>
        <td><%= veiculo.empresa.razao %></td>
        <td><%= (0<VeiculoMotorista.where('veiculo_id=? and status=?',veiculo.id,1).count() ? VeiculoMotorista.where('veiculo_id=? and status=?',veiculo.id,1).take.motorista.nome : 'Sem Motorista') %></td>
        <td><%= veiculo.placa %></td>
        <td><%= (0<VeiculoRastreador.where('veiculo_id=? and status=?',veiculo.id,1).count() ? VeiculoRastreador.where('veiculo_id=? and status=?',veiculo.id,1).take.rastreador.marca : 'Sem Rastreador') %></td>
        <td><%= veiculo.cor %></td>
        <td><%=l veiculo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_veiculo_path(veiculo), :class => 'btn btn-primary btn-xs' %>
          <%= link_to 'Motorista',veiculo_motoristas_path(:id => veiculo.id), :class => 'btn btn-success btn-xs' %>
          <%= link_to 'Rastreador',veiculo_rastreadores_path(:id => veiculo.id), :class => 'btn btn-info btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_veiculo_path,
            :class => 'btn btn-primary' %>

app/views/veiculos/new.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/veiculos/show.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:empresa_id) %>:</strong></dt>
  <dd><%= @veiculo.empresa_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:motorista_id) %>:</strong></dt>
  <dd><%= @veiculo.motorista_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:placa) %>:</strong></dt>
  <dd><%= @veiculo.placa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rastreador_id) %>:</strong></dt>
  <dd><%= @veiculo.rastreador_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cor) %>:</strong></dt>
  <dd><%= @veiculo.cor %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              veiculos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_veiculo_path(@veiculo), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              veiculo_path(@veiculo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>