config/routes.rb
Rails.application.routes.draw do
  resources :veiculo_rastreadores
  resources :veiculo_motoristas
  get 'page/index'

  get 'viagens/viagem' => 'viagens#viagem'
  get 'viagens/cria_viagem' => 'viagens#cria_viagem'

  post 'viagens/impcsv' => 'viagens#impcsv'
  get 'viagens/impcsv' => 'viagens#impcsv'

  post 'page/jornada' => 'page#jornada'

  get 'motoristas/autocomplete' => 'motoristas#autocomplete'

  get '/jornadaex' => 'page#jornadaex'

  resources :viagens
  resources :parada_empresas
  resources :ponto_paradas
  resources :tipo_paradas
  resources :eventos
  resources :tipo_eventos
  resources :veiculos
  resources :rastreadores
  resources :motoristas
  resources :empresas

  root 'page#index'

end

app/models/ponto_parada.rb
class PontoParada < ActiveRecord::Base
  belongs_to :tipo_parada
end

app/controllers/ponto_paradas_controller.rb
class PontoParadasController < ApplicationController
  before_action :set_ponto_parada, only: [:show, :edit, :update, :destroy]

  # GET /ponto_paradas
  # GET /ponto_paradas.json
  def index
    @ponto_paradas = PontoParada.all
  end

  # GET /ponto_paradas/1
  # GET /ponto_paradas/1.json
  def show
  end

  # GET /ponto_paradas/new
  def new
    @ponto_parada = PontoParada.new
  end

  # GET /ponto_paradas/1/edit
  def edit
  end

  # POST /ponto_paradas
  # POST /ponto_paradas.json
  def create
    @ponto_parada = PontoParada.new(ponto_parada_params)

    respond_to do |format|
      if @ponto_parada.save
        format.html { redirect_to @ponto_parada, notice: 'Ponto parada was successfully created.' }
        format.json { render :show, status: :created, location: @ponto_parada }
      else
        format.html { render :new }
        format.json { render json: @ponto_parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponto_paradas/1
  # PATCH/PUT /ponto_paradas/1.json
  def update
    respond_to do |format|
      if @ponto_parada.update(ponto_parada_params)
        format.html { redirect_to @ponto_parada, notice: 'Ponto parada was successfully updated.' }
        format.json { render :show, status: :ok, location: @ponto_parada }
      else
        format.html { render :edit }
        format.json { render json: @ponto_parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponto_paradas/1
  # DELETE /ponto_paradas/1.json
  def destroy
    @ponto_parada.destroy
    respond_to do |format|
      format.html { redirect_to ponto_paradas_url, notice: 'Ponto parada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ponto_parada
      @ponto_parada = PontoParada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ponto_parada_params
      params.require(:ponto_parada).permit(:descricao, :tipo_parada_id, :latitude, :longitude, :raio)
    end
end

app/helpers/ponto_paradas_helper.rb
module PontoParadasHelper
end

app/views/ponto_paradas/_form.html.erb
<%= form_for @ponto_parada, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label' %>
    <%= f.text_field :descricao, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tipo_parada_id, :class => 'control-label' %>
    <%= f.collection_select(:tipo_parada_id,TipoParada.all.order("descricao asc"),:id,:descricao,{}, :class => 'form-control') %>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <%= f.text_field :latitude, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <%= f.text_field :longitude, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :raio, :class => 'control-label' %>
    <%= f.text_field :raio, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ponto_paradas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ponto_paradas/edit.html.erb
<%- model_class = PontoParada -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ponto_paradas/index.html.erb
<%- model_class = PontoParada -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:tipo_parada_id) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:raio) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ponto_paradas.each do |ponto_parada| %>
      <tr>
        <td><%= link_to ponto_parada.id, ponto_parada_path(ponto_parada) %></td>
        <td><%= ponto_parada.descricao %></td>
        <td><%= ponto_parada.tipo_parada.descricao %></td>
        <td><%= ponto_parada.latitude %></td>
        <td><%= ponto_parada.longitude %></td>
        <td><%= ponto_parada.raio %></td>
        <td><%=l ponto_parada.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ponto_parada_path(ponto_parada), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ponto_parada_path(ponto_parada),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ponto_parada_path,
            :class => 'btn btn-primary' %>

app/views/ponto_paradas/new.html.erb
<%- model_class = PontoParada -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ponto_paradas/show.html.erb
<%- model_class = PontoParada -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @ponto_parada.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_parada_id) %>:</strong></dt>
  <dd><%= @ponto_parada.tipo_parada_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @ponto_parada.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @ponto_parada.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:raio) %>:</strong></dt>
  <dd><%= @ponto_parada.raio %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ponto_paradas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ponto_parada_path(@ponto_parada), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ponto_parada_path(@ponto_parada),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>